name: b3p
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Docker image
        run: docker build . -t my-container-image