name: npm-build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: ./
      - name: Build summary
        run: echo 'Build successful'
      - name: Verbose output
        run: echo 'Build finished successfully'
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app
          path: ./
      - name: Build Docker image
        run: |
          echo 'Building Docker image...'
          docker build . -t my-container-image
    needs: build
